### ISSUE TITLE
Funtor vs. Functor

### ISSUE THREAD

**Issue by M42** [M42/introCategorias#3]
**¿Existe algún criterio objetivo para elegir como traducir al castellano "functor" en este contexto?**

A falta de uno, estoy escribiendo "functor", para que conserve la similitud con el inglés.

**Comment by BraulioVM** [comment]
Bueno, por lo que he visto en toda la literatura al respecto (en español, claro) se utiliza la traducción *funtor*. Solo en el artículo de wikipedia viene la traducción de *functor* como válida. De todas formas, como bien dices no existe ninguna ventaja significativa para preferir funtor, así que mientras se use siempre el mismo no debería haber ningún problema.

**Comment by M42** [comment]
Tengo literatura en castellano usando *functor*.

* Apuntes de la UPV/EHU. *Marta Macho* - http://www.ehu.eus/~mtwmastm/CD0607.pdf
* Apuntes de la UV. *J. Clement Vidal* - http://www.uv.es/~jkliment/Documentos/TeoriaCategorias.pc.pdf

Pero dentro de la misma universidad ya cambian a *funtor*:

* Apuntes de la UV. *Carlos Ivorra* - http://www.uv.es/~ivorra/Libros/Algcom.pdf

En cualquier caso, es verdad que por cantidad gana *funtor*. Vamos a cambiarlo a la espera de un argumento de peso. La conclusión es esa:
> no existe ninguna ventaja significativa para preferir funtor, así que mientras se use siempre el 
> mismo no debería haber ningún problema.

**Comment by M42** [comment]
Funtor en castellano, ya sí lo he visto escrito en muchísimos sitios.
